---
title: "Building Municipal Capacity Project"
---

In groups, students will act as external consultants employed by a Council of Government (COG). The COG is concerned about their member organization's ability to implement increasingly complex policy solutions to networked problems. The COG wants your group to develop strategies to increase municipal capacity.

## Paper

Your group will develop a white paper recommending strategies to increase municipal capacity.

*Project definition.* Groups will prepare a memo defining "municipal capacity" and how to measure it. The purpose of this memo is to provide the scope of the recommendations in the full project.

*Strategy white paper.* Consistent with your group's definition of municipal capacity, your group will develop a white paper proposing strategies to increase municipal capacity. The white paper will include several strategies and your groups will rank these strategies in order of their impact and/or feasibility.

## Presentation

Groups will prepare a 10-12 minute presentation describing strategies to increase municipal capacity. The presentation should include a brief overview of the problem, the group's definition of municipal capacity, and the strategies proposed in the white paper.