---
title: "Weekly Check-in"
---

Every week, after you finish working through the content, I want to hear about what you learned and what questions you still have. This should be ≈150 words. That’s fairly short: there are ≈250 words on a typical double-spaced page in Microsoft Word (500 when single-spaced).

I will grade these check-ins using a check system:

-   ✓+: (11.5 points in gradebook) Response shows phenomenal thought and engagement with the course content. I will not assign these often.
-   ✓: (10 points in gradebook) Response is thoughtful, well-written, and shows engagement with the course content. This is the expected level of performance.
-   ✓-: (5 points in gradebook) Response is hastily composed, too short, and/or only cursorily engages with the course content. This grade signals that you need to improve next time. I will hopefully not assign these often.

Notice that is essentially a pass/fail or completion-based system. I’m not grading your writing ability, I’m not counting the exact number of words you’re writing, and I’m not looking for encyclopedic citations of every single reading to prove that you did indeed read everything. I’m looking for thoughtful engagement, that’s all. Do good work and you’ll get a ✓.

You will submit these check-ins via [Blackboard](https://webcourses.niu.edu).