---
title: Schedule
page-layout: full
tbl-colwidths: [10,40,7.5,7.5]
---

This page contains an outline of the topics, content, and assignments for the semester.
Note that this schedule will be updated as the semester progresses, with all changes documented here.

::: column-page-inset
| **Date** | **Topic** | **Content** | **Assignment** |
|--------|--------|:------:|:------:|
| {{< var classdates.week01 >}}    | **The local government landscape**          | [{{< fa book-open-reader >}}](/content/01-content.qmd) | |
| {{< var classdates.week02 >}}    | **Form & structure of local government**    | [{{< fa book-open-reader >}}](/content/02-content.qmd) | |
| {{< var duedates.paper-memo >}}    | Building Municipal Capacity project definition memo (submit by {{< var duedates.duetime >}})             | | [{{< fa pen-ruler >}}](assignment/building-municipal-capacity.qmd) |
| {{< var classdates.week03 >}}     | **Metropolitan & regional governance**      | [{{< fa book-open-reader >}}](/content/03-content.qmd) | |
| {{< var duedates.memo1 >}}      | Case 1 Due (submit by {{< var duedates.duetime >}})             | | [{{< fa pen-ruler >}}](assignment/01-memo.qmd) |
| {{< var classdates.week04 >}}     | **State-local intergovernmental relations** | [{{< fa book-open-reader >}}](/content/04-content.qmd) | |
| {{< var classdates.week05 >}}    | **External influences on local government** | [{{< fa book-open-reader >}}](/content/05-content.qmd) | |
| {{< var duedates.memo2 >}}    | Case 2 Due (submit by {{< var duedates.duetime >}})             | | [{{< fa pen-ruler >}}](assignment/02-memo.qmd) |
| {{< var classdates.week06 >}}    | **Metropolitan governance & service delivery approaches** | [{{< fa book-open-reader >}}](/content/06-content.qmd) | |
| {{< var classdates.week07 >}}    | **Community governance at a micro scale**   | [{{< fa book-open-reader >}}](/content/07-content.qmd) | |
| {{< var duedates.memo3 >}}       | Case 3 Due (submit by {{< var duedates.duetime >}})             | | [{{< fa pen-ruler >}}](assignment/03-memo.qmd) | 
| {{< var classdates.week08 >}}       | **Putting it all together**                 | [{{< fa book-open-reader >}}](/content/08-content.qmd) | |
| {{< var duedates.presentation >}}       | Building Municipal Capacity presentation due (submit by 5:00 PM) | | [{{< fa pen-ruler >}}](assignment/building-municipal-capacity.qmd#presentation) |
| {{< var duedates.paper >}}      | Building Municipal Capacity white paper due (submit by {{< var duedates.duetime >}} )   | | [{{< fa pen-ruler >}}](assignment/building-municipal-capacity.qmd) |
:::


